# Generated by Django 3.2.7 on 2021-09-26 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wms', '0001_initial'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenes',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='centro',
            name='sociedad',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Flotilla',
        ),
        migrations.RemoveField(
            model_name='kitp',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='kitp',
            name='producto_padre',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Ubicaciones',
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.almacenes'),
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_wms.centro'),
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_wms.producto'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_wms.producto'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.centro'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='preveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.proveedor'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.almacenes'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_wms.centro'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_wms.producto'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cat_wms.perfil'),
        ),
        migrations.DeleteModel(
            name='Almacenes',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Centro',
        ),
        migrations.DeleteModel(
            name='KitP',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Sociedad',
        ),
    ]
