# Generated by Django 3.2.7 on 2021-11-23 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('almacen', models.CharField(max_length=100)),
                ('nomenglatura', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('centro', models.CharField(max_length=100)),
                ('nomenglatura', models.CharField(max_length=10, verbose_name='Nomenclatura')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=50)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto1', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('estatus', models.CharField(choices=[('ALTA', 'ALTA'), ('BAJA', 'BAJA')], default='ALTA', max_length=40)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flotilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('placas', models.CharField(blank=True, max_length=6, null=True)),
                ('capacidad', models.CharField(blank=True, choices=[('1.5 TON', '1.5 TON'), ('3.5 TON', '3.5 TON'), ('8.0 TON', '8.0 TON')], max_length=50, null=True)),
                ('operador', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('tipo_usuario', models.PositiveSmallIntegerField(choices=[(1, 'Cliente'), (2, 'Administrador'), (3, 'Personal'), (4, 'Personal 2')], default=1)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto1', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('estatus', models.CharField(choices=[('ALTA', 'ALTA'), ('BAJA', 'BAJA')], default='ALTA', max_length=40)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('sociedad', models.CharField(max_length=250)),
                ('nomenglatura', models.CharField(max_length=10, verbose_name='Nomenclatura')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('ubicacion', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Clave')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ganancia', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_renta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_renta_mayoreo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reposicion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_frontal', models.ImageField(blank=True, null=True, upload_to='img_producto')),
                ('imagen_lateral', models.ImageField(blank=True, null=True, upload_to='img_producto')),
                ('imagen_posterior', models.ImageField(blank=True, null=True, upload_to='img_producto')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('alto', models.IntegerField(blank=True, null=True)),
                ('largo', models.IntegerField(blank=True, null=True)),
                ('ancho', models.IntegerField(blank=True, null=True)),
                ('volumen_cm3', models.IntegerField(blank=True, null=True)),
                ('peso_g', models.IntegerField(blank=True, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('piezas_caja', models.IntegerField(blank=True, null=True)),
                ('piezas_tarima', models.IntegerField(blank=True, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=120, null=True)),
                ('es_kit', models.BooleanField(default=False)),
                ('maximo', models.IntegerField(blank=True, null=True)),
                ('minimo', models.IntegerField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('LIBERADO', 'LIBERADO'), ('MANTENIMIENDO', 'MANTENIMIENTO'), ('BAJA', 'BAJA')], max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.proveedor')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
    ]
