# Generated by Django 3.2.7 on 2021-11-23 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat_wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centro',
            name='sociedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.sociedad'),
        ),
        migrations.AddField(
            model_name='almacenes',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.centro'),
        ),
    ]
