# Generated by Django 3.2.7 on 2021-11-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacenes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='centro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flotilla',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sociedad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={},
        ),
        migrations.AlterModelTable(
            name='almacenes',
            table='cat_almacenes',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='cat_categorias',
        ),
        migrations.AlterModelTable(
            name='centro',
            table='cat_centro',
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='cat_clientes',
        ),
        migrations.AlterModelTable(
            name='flotilla',
            table='cat_flotilla',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='cat_perfil',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='cat_producto',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='cat_provedores',
        ),
        migrations.AlterModelTable(
            name='sociedad',
            table='cat_sociedad',
        ),
        migrations.AlterModelTable(
            name='ubicaciones',
            table='cat_ubicaciones',
        ),
    ]
