# Generated by Django 3.2.7 on 2021-12-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wms', '0003_auto_20211123_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_wms.sociedad'),
        ),
    ]
