export interface Productos{
    nombre: string,
    descripcion: string,
    fecha_alta: Date,
    usuario: string,
    proveedor: string,
    codigo: string,
    modelo: string,
    categoria: string,
    precio_compra: number,
    ganancia: number,
    precio_renta: number,
    precio_renta_mayoreo: number,
    reposicion: number, 
    departamento: string,
    imagen_frontal: string,
    imagen_lateral: string,
    imagen_posterior: string,
    codigo_barras: string,
    alto: number,
    largo: number,
    ancho: number,
    volumen_cm3: number,
    peso_g: string,
    pais_origen: string,
    piezas_caja: number,
    piezas_tarima: number,
    clasificacion: string,
    observacion: string,
    es_kit: boolean,
    maximo: number,
    minimo: number,
    estatus: string,




}